### ISSUE TITLE
Complexity Explanations are showing up as invalid

### ISSUE THREAD

**Issue by SSimcox** [kisstkondoros/codemetrics-idea#3]
![codeMetrics](https://user-images.githubusercontent.com/15240900/60911819-483c5c00-a241-11e9-8887-60f474c0d653.png)
Before I updated to 1.0.2 When I clicked the traffic light in the gutter it would show me where the complexity for a method/class came from. Now it just shows as invalid for everything.
Intellij version: 2019.1.3
Plugin version: v1.0.2

**Comment by kisstkondoros** [comment]
This is strange, could you add any additional details about your environment? Does this happen with any project or just some of them? Which java version are you using?
Things like helps with reproducing the bug, without that there is not much I can do.

**Comment by kisstkondoros** [comment]
I've uploaded a new version (1.0.3) to the market which is hopefully fixing this problem.
Please let me know if it did not helped, since I wasn't able to reproduce this issue without mocking with the models at runtime.

Please note that the plugin will only appear for the public after Jetbrains did the review, it might take 1-2 business days.

**Comment by SSimcox** [comment]
Sorry I wasn't more communicative. The problem was fixed with 1.04 (I never installed 1.03). Thanks for this great work!
